### ISSUE TITLE
App Crashes when using withSliderBackgroundColor in Android 5.1

### ISSUE THREAD

**Issue by David-Molloy** [mikepenz/MaterialDrawer#1723]
```
Typeface font = Typeface.createFromAsset(getApplicationContext().getAssets(), "fonts/Roboto-Bold.ttf");
        result = new DrawerBuilder(this)
            //this layout have to contain child layouts
            .withRootView(R.id.drawer_container)
            .withToolbar(toolbar)
            .withDisplayBelowStatusBar(true)
            .withActionBarDrawerToggleAnimated(true)
            .addDrawerItems(
                    new PrimaryDrawerItem().withName("Plan My Route").withTextColor(getResources().getColor(R.color.white)).withTypeface(font).withSelectable(false),
                    new PrimaryDrawerItem().withName("Ddot Bus").withTextColor(getResources().getColor(R.color.white)).withTypeface(font).withSelectable(false),
                    new PrimaryDrawerItem().withName("Smart Bus").withTextColor(getResources().getColor(R.color.white)).withTypeface(font).withSelectable(false),
                    new PrimaryDrawerItem().withName("Reflex Bus").withTextColor(getResources().getColor(R.color.white)).withTypeface(font).withSelectable(false)
            )
            .withSavedInstance(savedInstanceState)
                .withSelectedItem(-1)
                .withSliderBackgroundColor(getColor(R.color.ETAHeader))
                .withOnDrawerItemClickListener(new Drawer.OnDrawerItemClickListener() {
                    @Override
                    public boolean onItemClick(View view, int position, IDrawerItem drawerItem)
                    {
                        drawerItem.withSelectable(false);
                        handleClick(position);
                        return false;
                    }
                }).build();
```
Logcat output below. Error appears at Line 73 which is .withSliderBackgroundColor(getColor(R.color.ETAHeader)). ETAHeader is a custom color which I am using else where within the app without any issue. Crash is only happening on 5.1. Works on android 6.0.

com.android.etadetroit E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.android.etadetroit, PID: 14241
                                                                        java.lang.NoSuchMethodError: No virtual method getColor(I)I in class Lcom/android/etadetroit/MainActivity; or its super classes (declaration of 'com.android.etadetroit.MainActivity' appears in /data/app/com.android.etadetroit-1/base.apk:classes32.dex)
                                                                            at com.android.etadetroit.MainActivity.onCreate(MainActivity.java:73)
                                                                            at android.app.Activity.performCreate(Activity.java:6010)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by mikepenz** [comment]
As your crash states. There is no such method like `getColor`

```
java.lang.NoSuchMethodError: No virtual method getColor(I)I in class 
```

use the `ContextCompat.getColor()` method instead
